# Generated by Django 5.2.8 on 2026-03-24 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bloodrequest', '0001_initial'),
        ('donors', '0001_initial'),
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospitals.hospitalprofile'),
        ),
        migrations.AddField(
            model_name='donoracceptance',
            name='donor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donors.donorprofile'),
        ),
        migrations.AddField(
            model_name='donoracceptance',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodrequest.bloodrequest'),
        ),
        migrations.AlterUniqueTogether(
            name='donoracceptance',
            unique_together={('donor', 'request')},
        ),
    ]
