# Generated by Django 5.2.8 on 2026-03-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequest', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='last_retry_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
