# Generated by Django 5.2.8 on 2026-03-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequest', '0003_bloodrequest_last_retry_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donoracceptance',
            name='status',
            field=models.CharField(choices=[('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='accepted', max_length=20),
        ),
    ]
