# Generated by Django 5.2.8 on 2026-03-27 21:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodrequest', '0004_alter_donoracceptance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donoracceptance',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='donoracceptance',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('confirmed', 'Confirmed'), ('ignored', 'Ignored')], default='pending', max_length=20),
        ),
    ]
