# Generated by Django 5.2.8 on 2026-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
