# Generated by Django 5.2.8 on 2026-03-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_alter_donorprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='full_name',
            field=models.CharField(default='Mary Slessor', max_length=255),
            preserve_default=False,
        ),
    ]
