# Generated by Django 5.2.8 on 2026-03-25 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0003_donorprofile_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='donorprofile',
            name='successful_donation',
            field=models.ImageField(default=0, upload_to=''),
        ),
    ]
