# Generated by Django 5.2.8 on 2026-03-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0004_donorprofile_successful_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='successful_donation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
