# Generated by Django 5.2.8 on 2026-03-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0005_alter_donorprofile_successful_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC')], max_length=2),
        ),
    ]
