# Generated by Django 5.2.8 on 2026-04-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0006_alter_donorprofile_genotype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donorprofile',
            name='blood_group',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], db_index=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='genotype',
            field=models.CharField(choices=[('AA', 'AA'), ('AS', 'AS'), ('SS', 'SS'), ('AC', 'AC'), ('SC', 'SC')], db_index=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='donorprofile',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
