# Generated by Django 5.2.8 on 2026-03-24 05:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('rc_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('hospital_type', models.CharField(choices=[('government', 'Government'), ('private', 'Private')], max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
    ]
