# Generated by Django 5.2.8 on 2026-03-24 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rc_number', models.CharField(max_length=15)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('is_verfied', models.BooleanField(default=False)),
            ],
        ),
    ]
