# Generated by Django 5.2.8 on 2026-03-24 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='name',
            new_name='full_name',
        ),
    ]
