# Generated by Django 5.2.8 on 2026-03-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_rename_name_hospitalprofile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalprofile',
            old_name='is_verfied',
            new_name='is_verified',
        ),
        migrations.AddField(
            model_name='hospitalprofile',
            name='hospital_type',
            field=models.CharField(choices=[('government', 'Government'), ('private', 'Private')], default='PRIVATE', max_length=20),
            preserve_default=False,
        ),
    ]
